# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-09 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0002_auto_20170809_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ranking',
            field=models.IntegerField(null=True),
        ),
    ]
