# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-11 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0003_auto_20170809_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='abv',
            field=models.DecimalField(decimal_places=0, max_digits=2, verbose_name='Alcohol by Volume (%)'),
        ),
        migrations.AlterField(
            model_name='beer',
            name='brewery',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='ranking',
            field=models.IntegerField(),
        ),
    ]
