# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-11 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0004_auto_20170811_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='abv',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Alcohol by Volume (%)'),
        ),
        migrations.AlterField(
            model_name='beer',
            name='brewery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beers', to='rankings.Brewery'),
        ),
    ]
