# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-11 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0005_auto_20170811_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='abv',
            field=models.DecimalField(decimal_places=0, max_digits=2, verbose_name='Alcohol by Volume (%)'),
        ),
    ]
